name: Release Nuget Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
          source-url: https://api.nuget.org/v3/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Test
      run: dotnet test
      working-directory: ./src/Endpoints.Test

    - name: Build project
      run: dotnet build -c Release
      working-directory: ./src/Endpoints

    - name: Generate a NuGet package
      run: dotnet pack --no-build -c Release -o . /p:PackageVersion=1.0.${{github.run_number}}
      working-directory: ./src/Endpoints

    - name: Push to GitHub package registry
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}}